VPATH = . ..\..\common\midi ..\..\common\uart
CPP  = g++.exe
CC   = gcc.exe
OBJ  = aka10.o midi_win.o 6850.o
LIBS = --no-export-all-symbols --add-stdcall-alias -lwinmm
CFLAGS = $(INCS) -DBUILDING_DLL=1 -I..\..\..\src -I..\..\common\midi  -I..\..\common\uart -O3

all: aka10.dll

clean:
	del *.o
	del *.dll

DLLWRAP=dllwrap.exe
DEFFILE=libaka10.def
STATICLIB=libaka10.a

aka10.dll: $(OBJ)
	$(DLLWRAP) $(OBJ) $(LIBS) -o aka10.dll

%.o: %.c
	$(CC) $(CFLAGS) -c $<
