CPP  = g++.exe
CC   = gcc.exe
OBJ  = aka31.o d71071l.o scsi_hd.o wd33c93a.o
LIBS = --no-export-all-symbols --add-stdcall-alias  
CFLAGS = $(INCS) -DBUILDING_DLL=1 -I..\..\..\src  

all: aka31.dll

clean:
	del *.o
	del *.dll

DLLWRAP=dllwrap.exe
DEFFILE=libaka31.def
STATICLIB=libaka31.a

aka31.dll: $(OBJ)
	$(DLLWRAP) $(OBJ) $(LIBS) -o aka31.dll

%.o: %.c
	$(CC) $(CFLAGS) -c $<
