VPATH = . ..\..\common\midi ..\..\common\uart
CPP  = g++.exe
CC   = gcc.exe
OBJ  = 16550.o midimax.o midi_win.o
LIBS = --no-export-all-symbols --add-stdcall-alias -lwinmm
CFLAGS = $(INCS) -DBUILDING_DLL=1 -I..\..\..\src -I..\..\common\midi  -I..\..\common\uart -O3

all: midimax.dll

clean:
	del *.o
	del *.dll

DLLWRAP=dllwrap.exe
DEFFILE=libmidimax.def
STATICLIB=libmidimax.a

midimax.dll: $(OBJ)
	$(DLLWRAP) $(OBJ) $(LIBS) -o midimax.dll

%.o: %.c
	$(CC) $(CFLAGS) -c $<
