VPATH = . ..\..\common\midi ..\..\common\uart
CPP  = g++.exe
CC   = gcc.exe
OBJ  = aka12.o midi_win.o scc2691.o
LIBS = --no-export-all-symbols --add-stdcall-alias -lwinmm
CFLAGS = $(INCS) -DBUILDING_DLL=1 -I..\..\..\src -I..\..\common\midi  -I..\..\common\uart -O3

all: aka12.dll

clean:
	del *.o
	del *.dll

DLLWRAP=dllwrap.exe
DEFFILE=libaka12.def
STATICLIB=libaka12.a

aka12.dll: $(OBJ)
	$(DLLWRAP) $(OBJ) $(LIBS) -o aka12.dll

%.o: %.c
	$(CC) $(CFLAGS) -c $<
