CPP  = g++.exe
CC   = gcc.exe
OBJ  = aka05.o
LIBS = -lwinmm
CFLAGS = $(INCS) -DBUILDING_DLL=1 -I..\..\..\src -O3

all: aka05.dll

clean:
	rm *.o
	rm *.dll

DEFFILE=libaka05.def
STATICLIB=libaka05.a

aka05.dll: $(OBJ)
	$(CC) -o aka05.dll -s -shared $(OBJ) $(LIBS) -Wl,--subsystem,windows

%.o: %.c
	$(CC) $(CFLAGS) -c $<
