CPP  = g++.exe
CC   = gcc.exe
OBJ  = aka05.o
LIBS = --no-export-all-symbols --add-stdcall-alias -lwinmm
CFLAGS = $(INCS) -DBUILDING_DLL=1 -I..\..\..\src -g3

all: aka05.dll

clean:
	del *.o
	del *.dll

DLLWRAP=dllwrap.exe
DEFFILE=libaka05.def
STATICLIB=libaka05.a

aka05.dll: $(OBJ)
	$(DLLWRAP) $(OBJ) $(LIBS) -o aka05.dll

%.o: %.c
	$(CC) $(CFLAGS) -c $<
